### ISSUE TITLE
Is string-value in PARAMETER_WRITE (0x2d) messages for string-type parameters (0x0a) '\0'-terminated?

### ISSUE THREAD

**Issue by wimalopaan** [crsf-wg/crsf#21]

**Comment by ajjjjjjjj** [comment]
Looking at: https://github.com/tbs-fpv/freedomtx/blob/c079f0151e3678fe3902ca82307733d20db1c4b6/radio/sdcard/taranis-x9/SCRIPTS/TOOLS/CROSSFIRE/device.lua#L301

it is \0 terminated.

**Comment by CapnBry** [comment]
It is in the same format you received it, and all strings are null-terminated in CRSF. From [CRSF_FRAMETYPE_PARAMETER_SETTINGS_ENTRY](https://github.com/crsf-wg/crsf/wiki/CRSF_FRAMETYPE_PARAMETER_SETTINGS_ENTRY)
> All strings are ASCII and sent null-terminated (e.g. "Hi" is sent 48 69 00)

Please stop using the issues tracker as a place to ask questions, the Discussion area is for that.

**Comment by wimalopaan** [comment]
I explicitly referred to https://github.com/crsf-wg/crsf/wiki/CRSF_FRAMETYPE_PARAMETER_WRITE.
The value type STRING isn't mentioned there nor the termination. So I think this is a docu issue and should be handled as such.

**Comment by CapnBry** [comment]
I guess I just assumed folks would understand the format of the data is the same going or coming, but I've updated it to be clearer.

**Comment by sk8board** [comment]
Bryan, I have to say issue 18, 20, 21, and 22 have been quite cryptic and difficult to understand. Where is the source? Who provided such information?

**Comment by CapnBry** [comment]
I'm not really sure I understand the first part of your statement.

Regarding the source though:
The problem is there is no authoritative source for any of this, it was never intended to be an open protocol. Everything here has come from me reading open source projects (many written by/for TBS) and writing ELRS/demo/reverse-engineering implementations for the past 5 years so there's plenty of unknowns as to the purpose of some values or the constraints TBS expects them to have. I have seen a TBS document (which is where the part about I2C in the wiki comes from) but the wiki is more complete than that document. I wrote all of the documentation in an attempt to formalize it and make it available, hoping that momentum would create a more active working body where major stakeholders can agree on changes.

**Comment by wimalopaan** [comment]
I have to say that the docu is very well written and complete and correct according to the extend I can see (e.g. elrsV3.lua or Openi6x-built-in). With this docu I was able to write a complete implementation myself ... ok, some LA traces were helpful. So, I want to say "many thanks" to you!
The issues I opened were only some minor unclearities (at least to me) or some minor bug.
